# Generated by Django 2.0.4 on 2018-04-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cargo_revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('other_revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('aircraft_fuel', models.DecimalField(decimal_places=2, max_digits=7)),
                ('aircraft_maintenance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('commissions', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ground_handling', models.DecimalField(decimal_places=2, max_digits=7)),
                ('salaries_wages', models.DecimalField(decimal_places=2, max_digits=7)),
                ('aircraft_lease', models.DecimalField(decimal_places=2, max_digits=7)),
                ('overheads', models.DecimalField(decimal_places=2, max_digits=7)),
                ('non_operating_items', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flight_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('departures', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rev_pax_miles', models.DecimalField(decimal_places=4, max_digits=7)),
                ('avail_seat_miles', models.DecimalField(decimal_places=4, max_digits=7)),
                ('fuel_gallons', models.DecimalField(decimal_places=2, max_digits=6)),
                ('financial_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.Month')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, choices=[(2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='statsdata',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.Year'),
        ),
        migrations.AddField(
            model_name='month',
            name='financial_year',
            field=models.ForeignKey(default=2017, on_delete=django.db.models.deletion.CASCADE, to='analyst.Year'),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='financial_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.Month'),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.Year'),
        ),
    ]
